services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5up3r53cr3t
    ports:
      - "5432:5432"
